name: Unit Tests
on: [push, pull_request]
jobs:
  Unit-Tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.13.0-beta.2"
          architecture: x64
      - uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: "1.8.3"
      - run: poetry install
      - run: poetry run pytest
