name: CI
on: [push, pull_request]
jobs:
  build-and-test:
    name: Build and run unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.13.2"
          architecture: x64
      - uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: "2.1.1"
      - run: poetry install
      - run: poetry run pytest
      - run: poetry build
      - name: "Upload Artifacts"
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
  pypi-release:
    name: Upload release to PyPI
    needs: build-and-test
    runs-on: ubuntu-latest
    environment:
      name: release
      url: https://pypi.org/p/legacy-cgi
    permissions:
      id-token: write
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    steps:
      - name: "Download Artifacts"
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
